function escapeCppString(value) {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\t/g, " ")
    .slice(0, 16);
}

export function generateArduinoSketch({
  songTitle,
  artist,
  pages,
  defaultHoldMs = 3000,
  hasTiming = false,
}) {
  const lyricEntries = pages
    .map(
      (page) =>
        `  {"${escapeCppString(page.line1)}", "${escapeCppString(page.line2)}", ${page.holdMs ?? defaultHoldMs}}`
    )
    .join(",\n");

  const pageCount = pages.length;
  const timingNote = hasTiming
    ? "holdMs per page = gap until next lyric line (from LRC)."
    : `Fixed ${defaultHoldMs}ms per page (no LRC timing available).`;

  return `/*
 * Arduino LCD Lyric Display
 * Song: ${songTitle} — ${artist}
 * Generated by arduino-lyric-display
 * Timing: ${timingNote}
 *
 * LCD: RS=12, EN=11, D4-D7=5,4,3,2
 */

#include <LiquidCrystal.h>

LiquidCrystal lcd(12, 11, 5, 4, 3, 2);

struct Lyric {
  char line1[17];
  char line2[17];
  unsigned long holdMs;  // time until next lyric line starts
};

Lyric lyrics[] = {
${lyricEntries || `  {"No lyrics found", "Paste in web app", ${defaultHoldMs}}`}
};

const int LYRIC_COUNT = ${pageCount || 1};

int currentPage = 0;
unsigned long lastChange = 0;

void showPage(int index) {
  lcd.clear();
  lcd.setCursor(0, 0);
  lcd.print(lyrics[index].line1);
  lcd.setCursor(0, 1);
  lcd.print(lyrics[index].line2);
}

void setup() {
  lcd.begin(16, 2);
  showPage(0);
  lastChange = millis();
}

void loop() {
  if (millis() - lastChange >= lyrics[currentPage].holdMs) {
    currentPage = (currentPage + 1) % LYRIC_COUNT;
    showPage(currentPage);
    lastChange = millis();
  }
}
`;
}
